@URL = https://web-production-66e36.up.railway.app

###
# Obtener todos los usuarios
GET {{URL}}/traer_usuarios

###
# Crear usuario
POST {{URL}}/nuevo_usuario
Content-Type: application/json

{
    "nombre": "Pablo",
    "apellido": "Navas",
    "provincia": "Misiones"
}

###
# Actualizar usuario con id=1
PUT {{URL}}/actualizar_usuario/1
Content-Type: application/json

{
    "nom": "Juan Actualizado"
}

###
# Eliminar usuario con id=1
DELETE {{URL}}/eliminar_usuario/1


### --- PRUEBAS DE ASISTENCIA ---


# Registrar una nueva asistencia (asumiendo que existe el usuario con id_usuario=1)
###
POST {{URL}}/nueva_asistencia
Content-Type: application/json

{
    "fecha": "2026-06-24 07:55:00",
    "estado": "Presente",
    "id_preceptor": 1,
    "id_alumno": 1
}

###
#Preceptor :D
POST {{URL}}/preceptor
Content-Type: application/json

{
    "nombre_usuario": "bubu",
    "email": "bubu.gere@sagradoalcal.edu.ar",
    "contraseña": 12345

    }

###
#Alumno :D
POST {{URL}}/alumno
Content-Type: application/json

{
    "nombre": "Belen",
    "apellido": "Diaz",
    "Cursos_idCursos": 1

    }

###
#curso :D
POST {{URL}}/curso
Content-Type: application/json

{
    "nombre_curso": "7B",
    "modalidad_idmodalidad": "Tecnica",
    
    }


###
# Obtener el historial de asistencias de todos los usuarios
GET {{URL}}/traer_asistencias